version: '3.8'

services:
  guardiao:
    image: guardiao
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./apps:/app/apps
    ports:
      - "5002:5000"  # Expõe a API do Flask para o host
    environment:
      - FLASK_APP=app.py
      - DB_ENGINE=mysql+pymysql
      - DB_USERNAME=guardiao
      - DB_PASS=guardiao_password
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=guardiao_db
    networks:
      - app-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=guardiao_db
      - MYSQL_USER=guardiao
      - MYSQL_PASSWORD=guardiao_password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root_password
    networks:
      - app-network
    depends_on:
      - mariadb

  wazuh-manager:
    image: wazuh/wazuh-manager:latest
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"  # Porta para receber logs dos agentes
      - "1515:1515/tcp"  # Porta para comunicação com os agentes
      - "55000:55000/tcp"  # Porta da API do Wazuh
    volumes:
      - wazuh-data:/var/ossec  # Volume para persistir dados do Wazuh
      - ./ossec-docker/conector:/opt/conector  # Mount the API connector
      - ./wazuh-config/entrypoint.sh:/entrypoint.sh  # Custom entrypoint script
    networks:
      - app-network
    environment:
      - FILEBEAT_SSL_VERIFICATION_MODE=none
      - INDEXER_URL=none
      - INDEXER_USERNAME=none
      - INDEXER_PASSWORD=none
      - ENABLE_FILEBEAT=0
      - DISABLE_DASHBOARD_MODULES=1
      - API_PASSWORD=sua_senha_secreta  # Password for the API
    entrypoint: ["/entrypoint.sh"]  # Use custom entrypoint
    depends_on:
      - zincsearch

  ossec-to-zinc:
    image: python:3.12-slim
    volumes:
      - ./zincsearch/ossec_to_zincsearch.py:/app/ossec_to_zincsearch.py
      - ./zincsearch/check_zinc.py:/app/check_zinc.py
      - ./zincsearch/ossec_to_zinc.sh:/app/ossec_to_zinc.sh
      - wazuh-data:/ossec/  # Updated to use wazuh-data volume
    command: bash /app/ossec_to_zinc.sh
    networks:
      - app-network
    depends_on:
      - zincsearch
      - wazuh-manager

  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    ports:
      - "4080:4080"  # Porta padrão do ZincSearch
    volumes:
      - zinc-data:/data  # Volume para persistir dados do ZincSearch
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=#Pascho7095
      - ZINC_DATA_PATH=/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  zinc-data:
  wazuh-data:  # Renamed from ossec-data to wazuh-data
  mariadb-data:  # Add this new volume for MariaDB data persistence

networks:
  app-network:
    driver: bridge