# Configurações internas do Wazuh
# Este arquivo contém opções de configuração avançadas

# Configurações gerais
logcollector.remote_commands=0
remoted.pass_empty_keyfile=0
analysisd.debug=0

# Configurações de desempenho
wazuh_database.interval=60
wazuh_database.max_queued_events=100000
logcollector.open_attempts=8

# Configurações de monitoramento
monitord.rotate_log=1
monitord.compress=1
monitord.sign=1
monitord.monitor_agents=1

# Configurações de alerta
analysisd.default_timeframe=360
analysisd.stats_interval=360
