# Wazuh Internal Configuration

# Logcollector
logcollector.remote_commands=0
logcollector.loop_timeout=2

# Remoted
remoted.pass_empty_keyfile=0

# Analysisd
analysisd.default_timeframe=360
analysisd.stats_interval=360

# Monitord
monitord.rotate_log=1
monitord.compress=1
monitord.sign=1
monitord.monitor_agents=1

# Integratord - Adicionando a configuração necessária
integrator.debug=0
integrator.max_retries=5
integrator.retry_interval=5

# Database
wazuh_database.interval=60
wazuh_database.max_queued_events=100000

# Execd
execd.max_restart_lock=600

# Auth - Adicionando configurações necessárias
authd.use_source_ip=0
auth.timeout_seconds=60
auth.use_password=0
auth.force_insert=0
auth.force_time=0
auth.use_source_ip=0
auth.pass_empty_keyfile=0
auth.timeout_seconds=60
auth.timeout_microseconds=1000000